clear; clc; close all;

paths = run_00_setup_branch_paths();

fprintf('====================================================\n');
fprintf('  Branch Baseline Labyrinth DeePC Run\n');
fprintf('====================================================\n');

config = branch_extract_demo_config( ...
    'RegenerateIfMissing', true, ...
    'NumSamples', 360, ...
    'Seed', 11, ...
    'TIni', 4, ...
    'TF', 8, ...
    'LambdaY', 700, ...
    'LambdaG', 12, ...
    'PathSpacing', 0.16, ...
    'UseTrainingSetpoints', true, ...
    'SolverName', 'auto', ...
    'SolverVerbose', false);

result = branch_run_labyrinth_rollout(config, ...
    'Label', 'branch_labyrinth_baseline', ...
    'ControllerMode', 'baseline', ...
    'MaxSteps', 280, ...
    'ValidateOriginal', true);

figDir = paths.baselineFiguresDir;
artifacts = branch_plot_labyrinth_results(result, figDir, 'branch_labyrinth_baseline');
result.artifacts = artifacts;

matFile = fullfile(paths.resultsDir, 'baseline_results.mat');
save(matFile, 'result');

fprintf('\nBaseline complete.\n');
fprintf('  QP success rate: %.1f%%\n', 100 * result.metrics.qpSuccessRate);
fprintf('  Position RMSE:   %.3f m\n', result.metrics.positionRmse);
fprintf('  Final error:     %.3f m\n', result.metrics.finalError);
fprintf('  Min h:           %.3f m\n', result.metrics.minSafetyMargin);
fprintf('  Saved MAT:       %s\n', matFile);
